First working version

diff --git a/complete-convert b/complete-convert
--- a/complete-convert
+++ b/complete-convert
@@ -40,21 +40,21 @@ fi
 # Change to cloned repository directory
 cd "${M}"
 
-# # Run xmllint on each to ensure each file is well-formed XML
-# echo "Verify files are well-formed..."
-# for file in *.html; do
-#     echo "==== $file"
-#     if [ "$file" = "js_toc.html" ]; then
-#         echo "Ignoring non-content file"
-#         continue
-#     fi
-# 
-#     # See if xmllint reports non-well-formed XML
-#     if [ ! "$(xmllint --nonet --noout $file 2>&1 | wc -c)" = "0" ]; then
-#         echo "ERROR: xmllint reported a problem"
-#         exit 1
-#     fi
-# done
+# Run xmllint on each to ensure each file is well-formed XML
+echo "Verify files are well-formed..."
+for file in *.html; do
+    echo "==== $file"
+    if [ "$file" = "js_toc.html" ]; then
+        echo "Ignoring non-content file"
+        continue
+    fi
+
+    # See if xmllint reports non-well-formed XML
+    if [ ! "$(xmllint --nonet --noout $file 2>&1 | wc -c)" = "0" ]; then
+        echo "ERROR: xmllint reported a problem"
+        exit 1
+    fi
+done
 
 # Extract title of each file to demo reading XML in Python
 echo "Beginning processing pipeline"
